consumer.py, settings.py
**Changes**
Triages transform (Common Software or XML) based on arbitrary value: 'file-type' = 'xml'
**How to test**
Use console app locally in full app setup and check xml/CS docs produced on correct request.
Requires sdx-transform-testform, sdx-transform-cs, sdx-console
Requires example data in sdx-transform-testform README
**Who can test**
Anyone but @jjeane
=> Transform testform

app/response_processor.py, app/settings.py, tests/test_data.py, tests/test_response_processor.py
**Changes**
Handles changes to census survey id and instrument id in json
**How to test**
Check travis build/ review tests. 
Submit a census and non census survey from console
**Who can test**
Anyone but @elliott-jenkins
=> handles changes to census survey id and instrument id

app/settings.py
**Changes**
Removed the extra config for the third rabbit queue
=> remove third queue

app/queue_publisher.py, app/response_processor.py
**Changes**
Enable fallback to a second queue
**How to test**
Check travis build/ review tests.
Run as part of sdx-compose
**Who can test**
Anyone but @elliott-jenkins
=> Queue publisher

.travis.yml, Dockerfile, Makefile, requirements.txt
Removes ``pip`` step from Dockerfile as dependencies are already satisfied in base image
=> Update 'requests' -> 2.12.4. Add makefile

app/consumer.py, app/settings.py
Repos affected:
- sdx-collect
- sdx-downstream
- sdx-receipt-ctp
- sdx-receipt-rrm
=> Removed delay queue publishing.

app/consumer.py, app/processors/common_software_processor.py
tx_id was being null'd after already being set.
Change which logger being used to ensure it's already bound with the tx_id
=> Fix logging of tx_id

app/helpers/request_helper.py
Corrects raising of exceptions when `remote_call` fails and handling of `None` objects.
=> Correct return exceptions for remote_call()

app/consumer.py
Changes 'nack for retry' to 'nack' to improve SDX logging.
=> Changes nack for retry to nack

CHANGELOG.md, app/helpers/request_helper.py, app/processors/common_software_processor.py
Changes status_code to status to improve SDX logging.
=> Changes status_code to status

CHANGELOG.md, app/consumer.py
Log tx_id for successful and unsuccessful FTP attempts
=> Log tx_id for FTP attempts

.travis.yml, CHANGELOG.md, Dockerfile, Makefile, app/async_consumer.py, app/consumer.py, app/settings.py, requirements.txt
Works in my sdx-compose locally.
Thrown together quite quickly so definitely look over before merging
=> addings common functionality and updating timezoning

Dockerfile, Makefile, test_requirements.txt
> What does this pull request change/fix? Why was it nessessary?
Fixes make dev issue with clean environments 
https://trello.com/c/5UZdTQJa/210-make-files-dont-work-in-clean-environments-2
=> Replacing make dev with make build

app/main.py
> What does this pull request change/fix? Why was it nessessary?
=> Not durable queue

CHANGELOG.md, Dockerfile
Remove sdx-common clone in docker.
=> Remove sdx-common clone in docker

CHANGELOG.md, app/helpers/request_helper.py, app/main.py, app/processors/common_software_processor.py, app/processors/cora_processor.py, app/processors/message_processor.py, app/settings.py, tests/test_cora_processor.py, tests/test_data.py
This pull request adds the functionality to handle cora surveys. This is necessary in order for this to be the singular downstream service for SDX.
=> [Merge with gitlab config] Add handling of cora

CHANGELOG.md, app/helpers/request_helper.py, app/settings.py, config.ini
Move all service config to application config file. This will make config easier to maintain.
=> Add config file and populate

.gitignore, .travis.yml, CHANGELOG.md, Makefile, test_requirements.txt
Implement pytest this should make test output more formalised.
=> Implement pytest

Dockerfile
=> Remove unnecessary steps from dockerfile

CHANGELOG.md, app/main.py, app/processors/common_software_processor.py, app/processors/cora_processor.py, app/processors/message_processor.py, app/processors/processor_base.py, tests/test_common_software_processor.py, tests/test_cora_processor.py, tests/test_data.py, tests/test_message_processor.py
> Refactored because the code was repeated in a few places . Also added tests to increase coverage 
-  CHANGELOG.md updated
=> Refactor processors

manifest-template.yml
> What does this pull request change/fix? Why was it necessary?  Add manifest-template.yml file for deployments to CF via Jenkins.
=> Add manifest-template for deployment to CF

manifest-template.yml
> What does this pull request change/fix? Why was it necessary? Add FTP params to manifest-template for deploying to CF via Jenkins
=> Add FTP params to manifest-template for deploying to CF via Jenkins

CHANGELOG.md, scripts/README.md, scripts/reprocess.py, scripts/tx_ids
Adding reprocessing scripts to the repo, because it's better they live here then as a script on a box, not in source control
=> Add reprocessing script

CHANGELOG.md, app/main.py
[trello](https://trello.com/c/P4jSIIfy/2504-ensure-all-sdx-services-log-their-version-on-startup)
=> Add startup log with version

tests/test_data.py
> E-Commerce form type should have been 0041
=> E-Commerce form type to 0041

tests/test_data.py
https://trello.com/c/mh0fa5HS/764-e-commerce-changes
Change formtype to 0051
=> Update instrument id on test data

CHANGELOG.md, app/helpers/request_helper.py, app/processors/message_processor.py, app/settings.py, tests/test_data.py, tests/test_message_processor.py
adds funcitonality to get feedback submission from sdx-store
- [ X ] CHANGELOG.md updated? (if required)
=> Automated feedback

CHANGELOG.md, app/processors/message_processor.py, scripts/reprocess.py, tests/test_message_processor.py
- [ X ] CHANGELOG.md updated? (if required)
=> changes in changelog, names, tests
